tls:
  certificates:
    - certFile: "/certs/_wildcard.docker.localhost.pem"
      keyFile: "/certs/_wildcard.docker.localhost-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/_wildcard.docker.localhost.pem"
        keyFile: "/certs/_wildcard.docker.localhost-key.pem"
